---
- name: Install Grafana
  hosts: all
  become: yes

  tasks:
    - name: Pull and run Grafana container
      docker_container:
        name: grafana
        image: grafana/grafana
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
        detach: yes