---
- name: Setup Address service with Node.js
  hosts: all
  become: yes

  tasks:
    - name: Install NVM
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash

    - name: Load NVM and install Node.js LTS
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install --lts

    - name: Create and setup Address directory
      file:
        path: /srv/address
        state: directory
        mode: '0755'

    - name: Initialize npm and install dependencies
      shell: |
        cd /srv/address
        npm init -y
        npm install express nodemon stream @elastic/elasticsearch
        npm install forever -g

    - name: Copy index.js
      copy:
        src: ../js/monolith.js
        dest: /srv/address/index.js
        mode: '0644'

    - name: Start the app using forever
      shell: forever start /srv/address/index.js